# Generated by Django 6.0.1 on 2026-02-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transmission",
                    models.CharField(
                        choices=[("Automatic", "Automatic"), ("Manual", "Manual")],
                        max_length=20,
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Hybrid", "Hybrid"),
                            ("Electric", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
